/**
 * Console Component
 * 
 * Handles message display, scrolling, and filtering.
 */

import type { ParsedMessage, DebugLevel } from '../types';

export class Console {
  private container: HTMLElement;
  private messages: ParsedMessage[] = [];
  private filteredMessages: ParsedMessage[] = [];
  private filterText = '';
  private autoScroll = true;
  private fontSize = 13;
  private messageIdCounter = 0;

  constructor(container: HTMLElement) {
    this.container = container;
    this.setupScrollListener();
  }

  /**
   * Setup scroll listener for auto-scroll detection
   */
  private setupScrollListener(): void {
    const scrollParent = this.container.parentElement;
    if (!scrollParent) return;

    scrollParent.addEventListener('scroll', () => {
      if (!this.autoScroll) return;
      
      const isAtBottom = scrollParent.scrollHeight - scrollParent.scrollTop 
        <= scrollParent.clientHeight + 50;
      
      // Show "new messages" button when scrolled up
      const scrollBtn = document.getElementById('scrollToBottomBtn');
      if (scrollBtn) {
        scrollBtn.hidden = isAtBottom;
      }
    });

    // Scroll to bottom button
    const scrollBtn = document.getElementById('scrollToBottomBtn');
    scrollBtn?.addEventListener('click', () => {
      this.scrollToBottom();
      scrollBtn.hidden = true;
    });
  }

  /**
   * Append a parsed message to the console
   */
  appendMessage(message: ParsedMessage): void {
    this.messages.push(message);
    
    // Apply filter
    if (this.matchesFilter(message)) {
      this.filteredMessages.push(message);
      this.renderMessage(message);
    }

    // Limit buffer size
    if (this.messages.length > 10000) {
      this.messages.shift();
      this.filteredMessages = this.messages.filter(m => this.matchesFilter(m));
      this.rerender();
    }

    if (this.autoScroll) {
      this.scrollToBottom();
    }
  }

  /**
   * Append a system message (generated by app, not device)
   */
  appendSystemMessage(text: string, level: 'info' | 'error' = 'info'): void {
    const message: ParsedMessage = {
      id: `msg-${++this.messageIdCounter}`,
      type: 'system',
      content: text,
      raw: text,
      receivedAt: Date.now(),
    };
    
    this.appendMessage(message);
  }

  /**
   * Render a single message to the DOM
   */
  private renderMessage(message: ParsedMessage): void {
    const row = document.createElement('div');
    row.className = `console__message console__message--${message.type}`;
    row.dataset.id = message.id;
    
    if (message.level) {
      row.classList.add(`console__message--level-${message.level}`);
    }

    // Build message content
    const parts: string[] = [];

    // Timestamp (if available)
    if (message.timestamp !== undefined) {
      parts.push(`<span class="msg-time">${this.formatTimestamp(message.timestamp)}</span>`);
    }

    // Level badge
    if (message.level) {
      const levelLetter = this.getLevelLetter(message.level);
      parts.push(`<span class="msg-level msg-level--${message.level}">[${levelLetter}]</span>`);
    }

    // Function and core (if available)
    if (message.function) {
      parts.push(`<span class="msg-func">(${message.function})</span>`);
    }
    if (message.core !== undefined) {
      parts.push(`<span class="msg-core">(C${message.core})</span>`);
    }

    // Message content
    parts.push(`<span class="msg-content">${this.escapeHtml(message.content)}</span>`);

    row.innerHTML = parts.join(' ');
    
    // Remove welcome message if present
    const welcome = this.container.querySelector('.console__welcome');
    if (welcome) {
      welcome.remove();
    }

    this.container.appendChild(row);
  }

  /**
   * Clear all messages
   */
  clear(): void {
    this.messages = [];
    this.filteredMessages = [];
    this.container.innerHTML = '';
  }

  /**
   * Set filter text
   */
  setFilter(text: string): void {
    this.filterText = text.toLowerCase();
    this.filteredMessages = this.messages.filter(m => this.matchesFilter(m));
    this.rerender();
  }

  /**
   * Check if message matches current filter
   */
  private matchesFilter(message: ParsedMessage): boolean {
    if (!this.filterText) return true;
    return message.content.toLowerCase().includes(this.filterText) ||
           message.raw.toLowerCase().includes(this.filterText);
  }

  /**
   * Re-render all filtered messages
   */
  private rerender(): void {
    this.container.innerHTML = '';
    
    for (const message of this.filteredMessages) {
      this.renderMessage(message);
    }

    if (this.autoScroll) {
      this.scrollToBottom();
    }
  }

  /**
   * Set auto-scroll enabled state
   */
  setAutoScroll(enabled: boolean): void {
    this.autoScroll = enabled;
    if (enabled) {
      this.scrollToBottom();
    }
  }

  /**
   * Set font size
   */
  setFontSize(size: number): void {
    this.fontSize = size;
    this.container.style.fontSize = `${size}px`;
  }

  /**
   * Scroll to bottom of console
   */
  scrollToBottom(): void {
    const scrollParent = this.container.parentElement;
    if (scrollParent) {
      scrollParent.scrollTop = scrollParent.scrollHeight;
    }
  }

  /**
   * Get plain text content for clipboard
   */
  getTextContent(): string {
    return this.filteredMessages
      .map(m => m.raw)
      .join('\n');
  }

  /**
   * Format timestamp from milliseconds
   */
  private formatTimestamp(ms: number): string {
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    
    const hh = String(hours % 24).padStart(2, '0');
    const mm = String(minutes % 60).padStart(2, '0');
    const ss = String(seconds % 60).padStart(2, '0');
    const mmm = String(ms % 1000).padStart(3, '0');
    
    return `${hh}:${mm}:${ss}.${mmm}`;
  }

  /**
   * Get single letter for debug level
   */
  private getLevelLetter(level: DebugLevel): string {
    const letters: Record<DebugLevel, string> = {
      1: 'V', 2: 'D', 3: 'I', 4: 'W', 5: 'E'
    };
    return letters[level] || '?';
  }

  /**
   * Escape HTML to prevent XSS
   */
  private escapeHtml(text: string): string {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }
}
